List<String> genderList = ['Male', 'Female', 'Others'];
List<String> usageTypeLists = [
  'A Relationship or date',
  'To get marry',
  'I\'m not sure',
  'Something Casual'
];

List<String> premiumFeatures = <String>[
  'Unlimited Swipes',
  'See who likes you',
  'Chat with anyone directly',
  'Advance filters'
];
List<String> blockReasonList = [
  'Fake Profile or Spam',
  'Inappropriate Messages',
  'Inappropriate Profile Photos',
  'Inappropriate bio',
  'Underage User',
  'Offline behaviour',
  'Asking Money',
  'Others'
];

List<String> interestTypeList = [
  'I\'m Interested in Men',
  'I\'m Interested in women',
  'I\'m Interested in everyone'
];
List<String> smokeList = ['Yes', 'No', 'Planning to quit', 'Occasionally'];
List<String> drinkList = ['Yes', 'No', 'Planning to quit', 'Occasionally'];
List<String> educationList = [
  'Graduate degree',
  'Undergraduate degree',
  'In college',
  'In grad school',
  'High school',
  'Vocational school',
  'I\'m not study',
  'Quit studies',
];
List<String> maritalStatusList = <String>[
  'Single',
  'Single with Kids',
  'Divorced',
  'Divorced with Kids',
  'Widowed',
  'Widowed with Kids',
  'Separated',
  'Separated with Kids',
  'Married',
  'Married with kids'
];

List<String> heightList = [
  '4\'1"',
  '4\'2"',
  '4\'3"',
  '4\'4"',
  '4\'5"',
  '4\'6"',
  '4\'7"',
  '4\'8"',
  '4\'9"',
  '5\'0"',
  '5\'1"',
  '5\'2"',
  '5\'3"',
  '5\'4"',
  '5\'5"',
  '5\'6"',
  '5\'7"',
  '5\'8"',
  '5\'9"',
  '6\'0"',
  '6\'1"',
  '6\'2"',
  '6\'3"',
  '6\'4"',
  '6\'5"',
  '6\'6"',
  '6\'7"',
  '6\'8"',
  '6\'9"',
  '7\'0"',
  '7\'1"',
  '7\'2"',
  '7\'3"',
  '7\'4"',
  '7\'5"',
  '7\'6"',
  '7\'7"',
  '7\'8"',
  '7\'9"',
  '8\'0"',
];

List<String> religionTypeList = [
  'Christians',
  'Muslims',
  'Hindus',
  'Chinese',
  'Buddhists',
  'Sikhs',
  'Jains',
  'Jews',
  'Spiritists',
  'Atheist',
  'zoroastrians',
  'Shintoists',
  'Bha\'is',
  'Neoreligionists',
  'Ethnoreligionists'
];

List<String> castTypeList = [
  '24 Manai Telugu Chettiar',
  '96 Kuli Maratha',
  'Aaru Nattu Vellala',
  'Achirapakkam Chettiar',
  'Ad Dharmi',
  'Adi Andhra',
  'Adi Dravidar',
  'Adi Karnataka',
  'Agamudayar / Arcot / Thuluva Vellala',
  'Agaram Vellan Chettiar',
  'Agarwal',
  'Agnikula Kshatriya',
  'Agrahari',
  'Agri',
  'Aguri / Ugra Kshatriya',
  'Aheriya',
  'Ahir Shimpi',
  'Ahirwar',
  'Ahom',
  'Ambalavasi',
  'Amma Kodava',
  'Anjana (Chowdary) Patel',
  'Arakh / Arakvanshiya',
  'Aramari / Gabit',
  'Arekatica',
  'Arora',
  'Arunthathiyar',
  'Arya Vysya',
  'Asathi',
  'Ayira Vysya',
  'Ayodhyavasi',
  'Ayyaraka',
  'Badaga',
  'Bagdi',
  'Baidya',
  'Bairagi',
  'Bairwa',
  'Baishnab',
  'Baishya',
  'Bajantri',
  'Balai',
  'Balija',
  'Balija Naidu',
  'Balija Reddy',
  'Banayat Oriya',
  'Banik',
  'Baniya',
  'Baniya - Bania',
  'Baniya - Kumuti',
  'Banjara',
  'Baori',
  'Barai',
  'Bargi',
  'Bari',
  'Baria',
  'Barnwal',
  'Barujibi',
  'Bavaria',
  'Bazigar',
  'Beldar',
  'Beri Chettiar',
  'Besta',
  'Bhand',
  'Bhandari',
  'Bhar',
  'Bharbhunja',
  'Bhatia',
  'Bhatraju',
  'Bhavasar Kshatriya',
  'Bhil',
  'Bhoi',
  'Bhovi',
  'Bhoyar',
  'Bhulia / Meher',
  'Billava',
  'Bind',
  'Bishnoi/Vishnoi',
  'Bondili',
  'Boyar',
  'Brahmakshtriya',
  'Brahmbatt',
  'Brahmin - Anavil',
  'Brahmin - Anaviln Desai',
  'Brahmin - Audichya',
  'Brahmin - Bagra',
  'Brahmin - Baidhiki/Vaidhiki',
  'Brahmin - Baragaon',
  'Brahmin - Bardai',
  'Brahmin - Barendra',
  'Brahmin - Bhargav',
  'Brahmin - Bhatt',
  'Brahmin - Bhojak',
  'Brahmin - Bhumihar',
  'Brahmin - Chaubisa',
  'Brahmin - Dadhich',
  'Brahmin - Daivadnya',
  'Brahmin - Dakaut',
  'Brahmin - Danua',
  'Brahmin - Deshastha',
  'Brahmin - Dhiman',
  'Brahmin - Dravida',
  'Brahmin - Embrandiri',
  'Brahmin - Garhwali',
  'Brahmin - Gaur',
  'Brahmin - Goswami/Gosavi',
  'Brahmin - Gujar Gaur',
  'Brahmin - Gurukkal',
  'Brahmin - Halua',
  'Brahmin - Havyaka',
  'Brahmin - Hoysala',
  'Brahmin - Iyengar',
  'Brahmin - Iyer',
  'Brahmin - Jangid',
  'Brahmin - Jhadua',
  'Brahmin - Jyotish',
  'Brahmin - Kanyakubj',
  'Brahmin - Karhade',
  'Brahmin - Khadayata',
  'Brahmin - Khandelwal',
  'Brahmin - Khedaval',
  'Brahmin - Kokanastha',
  'Brahmin - Kota',
  'Brahmin - Koteshwara / Kota (Madhwa )',
  'Brahmin - Kulin',
  'Brahmin - Kumaoni',
  'Brahmin - Madhwa',
  'Brahmin - Maithil',
  'Brahmin - Mevada',
  'Brahmin - Modh',
  'Brahmin - Mohyal',
  'Brahmin - Nagar',
  'Brahmin - Namboodiri',
  'Brahmin - Narmadiya',
  'Brahmin - Niyogi',
  'Brahmin - Others',
  'Brahmin - Paliwal',
  'Brahmin - Panda',
  'Brahmin - Pandit',
  'Brahmin - Panicker',
  'Brahmin - Pareek',
  'Brahmin - Pushkarna',
  'Brahmin - Rajgor',
  'Brahmin - Rarhi',
  'Brahmin - Rarhi/Radhi',
  'Brahmin - Rigvedi',
  'Brahmin - Rudraj',
  'Brahmin - Sakaldwipi',
  'Brahmin - Sanadya',
  'Brahmin - Sanketi',
  'Brahmin - Saraswat',
  'Brahmin - Sarua',
  'Brahmin - Saryuparin',
  'Brahmin - Shivalli (Madhva)',
  'Brahmin - Shivhalli',
  'Brahmin - Shri Gaud',
  'Brahmin - Shri Mali',
  'Brahmin - Shrimali',
  'Brahmin - Shukla Yajurvedi',
  'Brahmin - Sikhwal',
  'Brahmin - Smartha',
  'Brahmin - Sri Vaishnava',
  'Brahmin - Stanika',
  'Brahmin - Tapodhan',
  'Brahmin - Tyagi',
  'Brahmin - Vaidiki',
  'Brahmin - Vaikhanasa',
  'Brahmin - Valam',
  'Brahmin - Velanadu',
  'Brahmin - Vyas',
  'Brahmin - Zalora',
  'Brajastha Maithil',
  'Bunt (Shetty)',
  'CKP',
  'Chakkala Nair',
  'Chalawadi and Holeya',
  'Chambhar',
  'Chandravanshi Kahar',
  'Charan',
  'Chasa',
  'Chattada Sri Vaishnava',
  'Chaturth',
  'Chaudary',
  'Chaurasia',
  'Chennadasar',
  'Cherakula Vellalar',
  'Chero',
  'Chettiar',
  'Chhetri',
  'Chippolu (Mera)',
  'Choudhary',
  'Coorgi',
  'Dasapalanjika / Kannada Saineegar',
  'Deshmukh',
  'Desikar',
  'Desikar Thanjavur',
  'Devadiga',
  'Devandra Kula Vellalar',
  'Devang Koshthi',
  'Devanga',
  'Devanga Chettiar',
  'Devar/Thevar/Mukkulathor',
  'Devrukhe Brahmin',
  'Dhakad',
  'Dhanak',
  'Dhangar',
  'Dhanka',
  'Dhanuk',
  'Dheevara',
  'Dhiman',
  'Dhoba',
  'Dhor / Kakkayya',
  'Dommala',
  'Dosar / Dusra',
  'Dumal',
  'Dusadh (Paswan)',
  'Ediga',
  'Ediga /Goud (Balija)',
  'Elur Chetty',
  'Ezhava',
  'Ezhava Panicker',
  'Ezhava Thandan',
  'Ezhuthachan',
  'Gabit',
  'Gahoi',
  'Gajula / Kavarai',
  'Ganda',
  'Gandha Vanika',
  'Gandharb',
  'Gandla',
  'Gandla / Ganiga',
  'Ganiga',
  'Garhwali',
  'Garo / Garoda',
  'Gatti',
  'Gavandi',
  'Gavara',
  'Gavaria',
  'Gawali',
  'Ghisadi',
  'Ghumar',
  'Goala',
  'Goan',
  'Gomantak',
  'Gond',
  'Gondhali',
  'Gopal / Gopala',
  'Goud',
  'Gounder',
  'Gounder - Kongu Vellala Gounder',
  'Gounder - Nattu Gounder',
  'Gounder - Others',
  'Gounder - Urali Gounder',
  'Gounder - Vanniya Kula Kshatriyar',
  'Gounder - Vettuva Gounder',
  'Gowda',
  'Gowda - Kuruba Gowda',
  'Gramani',
  'Gudia',
  'Gujjar',
  'Gulahre',
  'Gupta',
  'Guptan',
  'Gurav',
  'Gurjar',
  'Haihaivanshi',
  'Halba Koshti',
  'Heggade',
  'Helava',
  'Holar',
  'Hugar (Jeer)',
  'Illaththu Pillai',
  'Intercaste',
  'Irani',
  'Isai Vellalar',
  'Jaalari',
  'Jaiswal',
  'Jandra',
  'Jangam',
  'Jangra - Brahmin',
  'Jat',
  'Jatav',
  'Jetty/Malla',
  'Jhadav',
  'Jijhotia Brahmin',
  'Jingar',
  'Jogi (Nath)',
  'Julaha',
  'Kachara',
  'Kadava Patel',
  'Kadia',
  'Kahar',
  'Kaibarta',
  'Kaikaala',
  'Kalal',
  'Kalanji',
  'Kalar',
  'Kalbelia',
  'Kalinga',
  'Kalinga Vysya',
  'Kalita',
  'Kalwar',
  'Kamboj',
  'Kamma',
  'Kamma Naidu',
  'Kanakkan Padanna',
  'Kandara',
  'Kandera',
  'Kanjar',
  'Kansari',
  'Kansyakaar',
  'Kanykubj Bania',
  'Kapu',
  'Kapu Naidu',
  'Kapu Reddy',
  'Karakala Bhakthula',
  'Karana',
  'Karkathar',
  'Karmakar',
  'Karni Bhakthula',
  'Karuneegar',
  'Kasar',
  'Kasaundhan',
  'Kasera',
  'Kashyap',
  'Kasukara',
  'Katiya',
  'Kavara',
  'Kavuthiyya/Ezhavathy',
  'Kayastha',
  'Kayastha (Bengali)',
  'Kerala Mudali',
  'Keshri (Kesarwani)',
  'Khandayat',
  'Khandelwal',
  'Kharwa',
  'Kharwar',
  'Khatik',
  'Khatri',
  'Kirar',
  'Kodava',
  'Kodikal Pillai',
  'Kokanastha Maratha',
  'Kokna',
  'Koli',
  'Koli Mahadev',
  'Koli Patel',
  'Komti /Arya Vaishya',
  'Kongu Chettiar',
  'Kongu Nadar',
  'Kongu Vellala Gounder',
  'Konkani',
  'Korama',
  'Kori',
  'Kori/Koli',
  'Kosthi',
  'Krishnavaka',
  'Kshatriya',
  'Kshatriya Kurmi',
  'Kshatriya Raju',
  'Kudumbi',
  'Kulal',
  'Kulalar',
  'Kulita',
  'Kumaoni Rajput',
  'Kumawat',
  'Kumbhakar',
  'Kumbhar',
  'Kumhar',
  'Kummari',
  'Kunbi',
  'Kunbi Lonari',
  'Kunbi Maratha',
  'Kunbi Tirale',
  'Kuravan',
  'Kurmi',
  'Kurmi/Kurmi Kshatriya',
  'Kurni',
  'Kuruba',
  'Kuruhina Shetty',
  'Kuruhini Chetty',
  'Kurumbar',
  'Kuruva',
  'Kushwaha (Koiri)',
  'Kutchi',
  'Lad',
  'Lambadi',
  'Laxminarayan gola',
  'Leva patel',
  'Leva patil',
  'Linga Balija',
  'Lingayath',
  'Lodhi Rajput',
  'Lohana',
  'Lohar',
  'Loniya',
  'Lubana',
  'Madhesiya/Kanu/Halwai',
  'Madiga',
  'Madivala / Dhobi',
  'Mahajan',
  'Mahar',
  'Mahendra',
  'Maheshwari',
  'Maheshwari / Meshri',
  'Mahishya',
  'Mahor',
  'Mahuri',
  'Mair Rajput Swarnkar',
  'Majabi',
  'Mala',
  'Mali',
  'Mallah',
  'Malviya Brahmin',
  'Malwani',
  'Mangalorean',
  'Manipuri',
  'Manjapudur Chettiar',
  'Mannadiyar',
  'Mannan / Velan / Vannan',
  'Mapila',
  'Maratha',
  'Maratha Kshatriya',
  'Maruthuvar',
  'Matang',
  'Mathur',
  'Mathur Vaishya',
  'Matia Patel',
  'Maurya / Shakya',
  'Meena',
  'Meenavar',
  'Meghwal',
  'Mehar',
  'Mehra',
  'Meru Darji',
  'Mochi',
  'Modak',
  'Modh Ghanchi',
  'Modi',
  'Modikarlu',
  'Mogaveera',
  'Mudaliyar',
  'Mudiraj',
  'Munnuru Kapu',
  'Musahar',
  'Musukama',
  'Muthuraja / Mutharaiyar',
  'Naagavamsam',
  'Nabit',
  'Nadar',
  'Nagaralu',
  'Nai / Nayi Brahmin',
  'Naicker',
  'Naicker - Others',
  'Naicker - Vanniya Kula Kshatriyar',
  'Naidu',
  'Naik',
  'Nair',
  'Namasudra / Namassej',
  'Nambiar',
  'Namdarlu',
  'Nanjil Mudali',
  'Nanjil Nattu Vellalar',
  'Nanjil Vellalar',
  'Nanjil pillai',
  'Nankudi Vellalar',
  'Napit',
  'Nat',
  'Nattu Gounder',
  'Nattukottai Chettiar',
  'Nayaka',
  'Neeli',
  'Neeli Saali',
  'Nema',
  'Nepali',
  'Nessi',
  'Nhavi',
  'Niari',
  'Odan',
  'Ontari',
  'Oraon',
  'Oswal',
  'Otari',
  'Othuvaar',
  'Padmasali',
  'Padmashali',
  'Padmavati Porwal',
  'Pagadala',
  'Pal',
  'Pallan / Devandra Kula Vellalan',
  'Panan',
  'Panchal',
  'Pandaram',
  'Pandiya Vellalar',
  'Panicker',
  'Pannirandam Chettiar',
  'Paravan / Bharatar',
  'Parit',
  'Parkavakulam / Udayar',
  'Parsi',
  'Partraj',
  'Parvatha Rajakulam',
  'Pasi',
  'Paswan / Dusadh',
  'Patel',
  'Pathare Prabhu',
  'Patil',
  'Patnaick/Sistakaranam',
  'Patra',
  'Pattinavar',
  'Pattusali',
  'Patwa',
  'Perika',
  'Perika/Puragiri Kshatriya',
  'Pillai',
  'Poddar',
  'Poosala',
  'Porwal',
  'Porwal / Porwar',
  'Poundra',
  'Prajapati',
  'Pulaya / Cheruman',
  'Rabari',
  'Radhi / Niari',
  'Raigar',
  'Rajaka / Vannar',
  'Rajastani',
  'Rajbhar',
  'Rajbonshi',
  'Rajpurohit',
  'Rajput',
  'Raju / Kshatriya Raju',
  'Ramanandi',
  'Ramdasia',
  'Ramgariah',
  'Ramoshi',
  'Rastogi',
  'Rathi',
  'Rauniar',
  'Ravana Rajput',
  'Ravidasia',
  'Rawat',
  'Reddy',
  'Relli',
  'Rohit / Chamar',
  'Ror',
  'SC',
  'SKP',
  'ST',
  'Sadgope',
  'Sadhu Chetty',
  'Sagara (Uppara)',
  'Saha',
  'Sahariya',
  'Sahu',
  'Saini',
  'Saiva Pillai Thanjavur',
  'Saiva Pillai Tirunelveli',
  'Saiva Vellan chettiar',
  'Saliya',
  'Saliyar',
  'Salvi',
  'Samagar',
  'Sambava',
  'Sansi',
  'Sargara',
  'Sathwara',
  'Satnami',
  'Savji',
  'Senai Thalaivar',
  'Senguntha Mudaliyar',
  'Sengunthar/Kaikolar',
  'Settibalija',
  'Setty Balija',
  'Shah',
  'Shaw / Sahu/Teli',
  'Shettigar',
  'Shilpkar',
  'Shimpi/Namdev',
  'Sindhi',
  'Sindhi-Amil',
  'Sindhi-Baibhand',
  'Sindhi-Bhanusali',
  'Sindhi-Bhatia',
  'Sindhi-Chhapru',
  'Sindhi-Dadu',
  'Sindhi-Hyderabadi',
  'Sindhi-Larai',
  'Sindhi-Larkana',
  'Sindhi-Lohana',
  'Sindhi-Rohiri',
  'Sindhi-Sahiti',
  'Sindhi-Sakkhar',
  'Sindhi-Sehwani',
  'Sindhi-Shikarpuri',
  'Sindhi-Thatai',
  'Sirvi / Janwa',
  'Sonar',
  'Sondhia',
  'Soni',
  'Sonkar',
  'Sourashtra',
  'Sozhia Chetty',
  'Sozhiya Vellalar',
  'Srisayana',
  'Sugali (Naika)',
  'Sunari',
  'Sundhi',
  'Surya Balija',
  'Suthar',
  'Swakula Saali',
  'Swakula Sali',
  'Swarnakar',
  'Tamboli',
  'Tammali',
  'Tanti',
  'Tantubai',
  'Telaga',
  'Teli',
  'Telugupatti',
  'Thakkar',
  'Thakore',
  'Thakur',
  'Thandan',
  'Tharakan',
  'Thigala',
  'Thiyya',
  'Thiyya Thandan',
  'Thogata Veera Kshatriya',
  'Thogata Veerakshathriya',
  'Thondai Mandala Vellalar',
  'Thota',
  'Tili',
  'Tiyar/Tiar',
  'Togata',
  'Tonk Kshatriya',
  'Turupu Kapu',
  'Ummar / Umre / Bagaria',
  'Urali Gounder',
  'Urs',
  'Vada Balija',
  'Vadambar',
  'Vadar',
  'Vaddera',
  'Vadugan',
  'Vaish',
  'Vaishnav',
  'Vaishnav Dishaval',
  'Vaishnav Kapol',
  'Vaishnav Khadyata',
  'Vaishnav Lad',
  'Vaishnav Modh',
  'Vaishnav Porvad',
  'Vaishnav Shrimali',
  'Vaishnav Sorathaiya',
  'Vaishnav Vania',
  'Vaishnava',
  'Vaishya',
  'Vaishya Vani',
  'Valar',
  'Valluvan',
  'Valmiki',
  'Valsad',
  'Vani',
  'Vani / Vaishya',
  'Vania',
  'Vanika Vyshya',
  'Vaniya',
  'Vaniya Chettiar',
  'Vanjara',
  'Vanjari',
  'Vankar',
  'Vannar',
  'Vannia Kula Kshatriyar',
  'Vanyakulakshatriya',
  'Variar',
  'Varshney',
  'Varshney (Barahseni)',
  'Veera Saivam',
  'Veerakodi Vellala',
  'Velaan',
  'Velama',
  'Vellala Pillai',
  'Vellalar',
  'Vellan Chettiars',
  'Veluthedathu Nair',
  'Vettuva Gounder',
  'Vettuvan',
  'Vijayvargia',
  'Vilakithala Nair',
  'Vilakkithala Nair',
  'Vishwakarma',
  'Viswabrahmin',
  'Vokkaliga',
  'Vysya',
  'Yadav',
  'Yadava Naidu',
  'Yellapu',
  'Anavil Brahmin',
  'Audichya Brahmin',
  'Barendra Brahmin',
  'Bhatt Brahmin',
  'Bhumihar Brahmin',
  'Daivadnya Brahmin',
  'Danua Brahmin',
  'Deshastha Brahmin',
  'Dhiman Brahmin',
  'Dravida Brahmin',
  'Embrandiri Brahmin',
  'Garhwali Brahmin',
  'Gaur Brahmin',
  'Goswami/Gosavi Brahmin',
  'Gujar Gaur Brahmin',
  'Gurukkal Brahmin',
  'Halua Brahmin',
  'Havyaka Brahmin',
  'Hoysala Brahmin',
  'Iyengar Brahmin',
  'Iyer Brahmin',
  'Jangid Brahmin',
  'Jhadua Brahmin',
  'Kanyakubj Brahmin',
  'Karhade Brahmin',
  'Kokanastha Brahmin',
  'Kota Brahmin',
  'Kulin Brahmin',
  'Kumaoni Brahmin',
  'Madhwa Brahmin',
  'Maithil Brahmin',
  'Modh Brahmin',
  'Mohyal Brahmin',
  'Nagar Brahmin',
  'Namboodiri Brahmin',
  'Narmadiya Brahmin',
  'Niyogi Brahmin',
  'Panda Brahmin',
  'Pandit Brahmin',
  'Pushkarna Brahmin',
  'Rarhi Brahmin',
  'Rigvedi Brahmin',
  'Rudraj Brahmin',
  'Sakaldwipi Brahmin',
  'Sanadya Brahmin',
  'Sanketi Brahmin',
  'Saraswat Brahmin',
  'Saryuparin Brahmin',
  'Shivhalli Brahmin',
  'Shrimali Brahmin',
  'Sikhwal Brahmin',
  'Smartha Brahmin',
  'Sri Vaishnava Brahmin',
  'Stanika Brahmin',
  'Tyagi Brahmin',
  'Vaidiki Brahmin',
  'Vaikhanasa Brahmin',
  'Velanadu Brahmin',
  'Vyas Brahmin',
  'Shetty',
  'Mera',
  'Mukkulathor',
  'Paswan',
  'Jeer',
  'Brahmin Jijhotia',
  'Nath',
  'Koiri',
  'Brahmin Malviya',
  'Darji',
  'Amil Sindhi',
  'Baibhand Sindhi',
  'Bhanusali Sindhi',
  'Bhatia Sindhi',
  'Chhapru Sindhi',
  'Dadu Sindhi',
  'Hyderabadi Sindhi',
  'Larai Sindhi',
  'Larkana Sindhi',
  'Lohana Sindhi',
  'Rohiri Sindhi',
  'Sahiti Sindhi',
  'Sakkhar Sindhi',
  'Sehwani Sindhi',
  'Shikarpuri Sindhi',
  'Thatai Sindhi',
  'Naika',
  'Other Caste',
  'Don\'t wish to specify',
];
